robotoff/cli/annotate.py
=> missing HTTP header

data/ocr/logo_annotation_brands.txt, data/ocr/regex_brands.txt, data/ocr/regex_stores.txt
Some Aldi, Edeka, Lidl, and Woolworth store brands.
=> Add a few more store brands

data/ocr/packaging.txt
=> Added prefixes for fr: + es: sample

data/ocr/packaging.txt
adding more languages for bottle trick
=> adding more languages for bottle trick

data/ocr/store_regex.txt
=> swiss-knife

.github/workflows/crowdin.yml, crowdin.yml
Migrate Crowdin to GitHub Actions
=> Migrate Crowdin to GitHub Actions

robotoff/app/api.py, robotoff/scheduler/__init__.py, robotoff/settings.py, robotoff/workers/listener.py, services/ann/api.py, services/ann/settings.py
Needed to be able to start a dev robotoff instance
=> Parameterise sentry

doc/introduction/notifications.md
=> Add a notifications doc page

robotoff/elasticsearch/category/preprocessing.py
Add common words for Spain and Italy. Add some words for France. Should improve recall.
- #379
=> More category preprocessing

.github/workflows/crowdin.yml
- Reduce Crowdin runs to strict necessary
- This will trigger it on a branch `translations-trigger`
=> Reduce Crowdin runs to strict necessary

.github/workflows/robotoff.yml
Reverts openfoodfacts/robotoff#388 to investigate whether this was breaking the image building
=> Revert "Bump snok/install-poetry from 1.1.1 to 1.1.8"

.github/workflows/robotoff.yml
Reverts openfoodfacts/robotoff#398 - this commit is not the issue, rolling forward
FYI @teolemon
=> Revert "Revert "Bump snok/install-poetry from 1.1.1 to 1.1.8""

robotoff/elasticsearch/product/dump.py
Not 100% sure if this is the correct solution  - but at least the code will no longer crash on elasticsearch exports so I can unblock with the dev server work.
=> Fix incorrect function name

robotoff/app/api.py, robotoff/app/core.py
Reverts openfoodfacts/robotoff#368
=> Revert "Fix incorrect peewee query"

README.md
=> fix doc links in README

.github/workflows/container-build.yml, .github/workflows/container-deploy-ml.yml, .github/workflows/container-deploy.yml, .github/workflows/generate-docs.yml, .github/workflows/release-please.yml, .github/workflows/tfmodels-sync.yml
`$default-branch` only works in workflow templates, not in workflows.
My bad :)
=> ci: use default branch

robotoff/insights/_enum.py, robotoff/slack.py, tests/test_slack.py
An example of the new image alerting can be found [here](https://app.slack.com/client/T02KVRT1Q/C02P0PR5VS4)
=> Add structured messages to Slack alerting

robotoff/logos.py, robotoff/models.py, robotoff/workers/tasks/import_image.py, tests/test_models.py
Purposefully did not add tests to the import_image code as I don't understand what it should be doing.
Hopefully this is OK for the time being, we should probably take a better look at ANN anyway, since it seems to be having some issues.
=> Fix logo annotation Slack alerting

Dockerfile
Do not issue a chown command but copy with right user:group instead
=> ops: fix Dockerfile to be faster, fixes #482

.github/workflows/container-deploy.yml, Makefile
=> fix: remove init tasks

.github/workflows/models-deploy.yml, .github/workflows/pypi.yml
This PR prepares deployment to production for Robotoff.
=> ci: prod deployment prep

docker-compose.yml, docker/dev.yml, robotoff/settings.py, robotoff/workers/tasks/product_updated.py
It is useful for some specific operations.
=> feat: make wait on product update a parameter

README.md
=> docs: fix bold word

.github/labeler.yml, .github/workflows/label.yml
Start auto-labeling PRs
- This PR itself has been auto-labeled 🤯 
- #375
=> Start auto-labeling PRs

Makefile, robotoff/insights/importer.py, robotoff/prediction/category/neural/category_classifier.py, robotoff/prediction/types.py, robotoff/workers/tasks/product_updated.py, tests/integration/insights/test_category_import.py, tests/unit/workers/tasks/test_product_updated.py
=> feat: make neural category apply automatically

.github/workflows/container-deploy.yml, docker-compose.yml, gunicorn.py
for we need to take into account memory consumption
**WARNING** This PR merges against v1.1.0
=> fix: set num workers in gunicorn from env

.github/workflows/container-deploy.yml, docker-compose.yml, gunicorn.py
merge v1.1.0-hotfixes and deploy on preprod
=> Deploy preprod v1.1.0 hotfix0

robotoff/models.py
as this is used by api and hunger game
To run on postgres:
```
CREATE INDEX product_insight_type ON public.product_insight USING btree (type);
```
=> performance: add index on type

robotoff/metrics.py, robotoff/scheduler/__init__.py
at scheduler startup, fixes #557
=> fix: ensure influxdb database exists

tests/integration/insights/test_process_insights.py, tests/unit/test_slack.py
Added a test for category insights processing
=> test: category insights processing tests

CHANGELOG.md, doc/introduction/architecture.md, pyproject.toml
- update docs
- prepare release (I had to do it manually for we have no user facing changes)
=> feat: Update doc and prepare release

poetry.lock, pyproject.toml, robotoff/app/api.py, robotoff/insights/importer.py, robotoff/logos.py, robotoff/prediction/object_detection/core.py, robotoff/slack.py, tests/conftest.py, tests/integration/insights/test_category_import.py, tests/integration/insights/test_process_insights.py, tests/integration/models_utils.py, tests/integration/test_annotate_image.py, tests/integration/test_api.py, tests/integration/test_models_integration.py, tests/unit/test_slack.py
* Factory for Insight creation
* introduce factory boy
* Add tests on logo annotation
=> fix: add tests on logo annotation, introduce factory boy and fix logo annotation

robotoff/insights/annotate.py, robotoff/scheduler/__init__.py, tests/integration/insights/test_annotate.py, tests/integration/insights/test_process_insights.py, tests/integration/test_scheduler.py
it should caught single exception in annotate to continue with other annotations.
fixes #605
=> fix: avoid process_insight failing for all

README.md
- doc: Start of a doc update for Insights and Predictions
=> doc: Start of a doc update for Insights and Predictions

Makefile, robotoff/insights/importer.py, robotoff/logos.py, robotoff/prediction/ocr/core.py, robotoff/prediction/ocr/dataclass.py, robotoff/workers/tasks/import_image.py, robotoff/workers/tasks/product_updated.py
f-string are cool, but sentry can't group message. It is recommended to use % formating with arguments.
=> fix: change error messages to enable sentry grouping

robotoff/taxonomy.py
The timeout to fetch taxonomies was a bit too small ! Always failing in preprod for example…
=> fix: fix timeout issue on fetch taxonomy

robotoff/insights/annotate.py, robotoff/insights/importer.py, robotoff/logos.py, robotoff/off.py, robotoff/prediction/ocr/dataclass.py, robotoff/products.py, robotoff/slack.py, robotoff/taxonomy.py, robotoff/workers/tasks/import_image.py, robotoff/workers/tasks/product_updated.py
This is a continuation of 15abbeb8ca6 (#654)
I forgot some logs where there was a newline !
It's a bit urgent because robotoff is spamming my mailbox !
=> fix: fix log message for sentry grouping

.github/workflows/autoblack.yml, tests/integration/test_api.py
Add a test on questions pagination. This was done because of #683 but indeed it was already fixed !
=> refactor: add test on questions pagination

.github/workflows/semantic-pr.yml
- ci: use ci like on other repositories
=> ci: use ci like on other repositories

doc/introduction/contributing.md
- Updated documentation. This PR contains some minor additions to the contribution documentation.
- #761
=> doc: Updating documentation with details of installation for Windows

doc/introduction/architecture.md, robotoff/models.py
Some documentation (after looking through the code).
=> doc: add doc about image prediction

doc/introduction/contributing.md
Updating Robotoff document
- #689
=> doc: Robotoff doc update

Makefile, doc/how-to-guides/test-and-debug.md, robotoff/prediction/ocr/packager_code.py, tests/unit/prediction/ocr/test_packager_code.py
- Added a regex expression to test gluten code in packaging.
- #249
=> feat: Adding a regex for gluten packaging code

robotoff/off.py, tests/integration/test_api.py
- Writing a test case to check if the authenticated user still needs votes to get the question answered.
tests
- #801
=> feat: Test case to test if we need 3 votes (sent with user id) to get the question answered definitely 

doc/how-to-guides/test-and-debug.md
=> doc: fix formating in test-and-debug.md

.github/dependabot.yml
- ci: add dependabot updates for docker
=> ci: add dependabot updates for docker

robotoff/prediction/ocr/image_flag.py
- feat: detect cat images (opff)
=> feat: detect cat images (opff)

robotoff/app/api.py, robotoff/app/core.py, tests/integration/test_api.py
- Added `server_domain` to all "Collection" class ([First step from here](https://github.com/openfoodfacts/robotoff/issues/618#issuecomment-1235475222))
- #618
=> fix: Added server_domain all "Collection" class

robotoff/app/api.py
- Added `server_domain` parameter to the UnansweredQuestionsCollection API
- #618
=> feat: add server_domain parameter to the UnansweredQuestionsCollection API

.github/workflows/top-issues.yml
=> ci: Test top issues

doc/how-to-guides/test-and-debug.md
- adding documentation in [Test and Debug](https://openfoodfacts.github.io/robotoff/how-to-guides/test-and-debug/) about the make checks command.
=> doc: Missing make checks

robotoff/app/api.py, robotoff/app/core.py, tests/integration/test_api.py, tests/integration/test_core_integration.py
- Added `country `parameter to the `UnansweredQuestionCollection` API.
- #901
=> feat: Filter product by country to get answered questions

robotoff/app/api.py, robotoff/app/core.py
There is no need to display these questions as the insight is applied automatically max 5 minutes later.
=> fix: don't display questions about insights that are automatically applicable

robotoff/prediction/ocr/image_flag.py
Too many false positive for Gesture, and Thumb is expected
=> fix: remove some moderation cloud vision labels

doc/references/api.yml, robotoff/app/api.py, robotoff/app/core.py, robotoff/insights/importer.py, robotoff/models.py, robotoff/taxonomy.py, tests/unit/insights/test_importer.py
Implements https://github.com/openfoodfacts/robotoff/issues/947
=> feat: add annotation campaigns

robotoff/app/api.py, robotoff/app/schema.py, robotoff/taxonomy.py, tests/integration/test_annotate_image.py, tests/unit/test_taxonomy.py
- feat: support providing taxonomized value as input during logo annotation
- feat: improve request validation during logo annotation
=> feat: improve logo annotation route

robotoff/cli/insights.py, robotoff/cli/main.py, robotoff/products.py
- filter by predictor, value_tag, and scan count
- show the number of impacted insights
- add a dry run mode
- Document the CLI
=> feat: Improve apply-insight CLI command

.dockerignore, .gitignore, Makefile, robotoff/cli/main.py, scripts/ocr/run_ocr.py
- improve Makefile
- update run_ocr.py script
- update .gitignore and .dockerignore
- add new CLI command to export logos for logo cropping
=> feat: various fixes (improve Makefile - update run_ocr.py, .gitignore, .dockerignore - new CLI command to export logos for logo cropping)

robotoff/logos.py, robotoff/workers/tasks/import_image.py, tests/integration/test_annotate_image.py, tests/unit/test_logos.py
- fix: filter logos that are almost exactly the same
- feat: add `data->bounding_box` field in logo derived insights
- feat: improve `generate_prediction` function
=> feat: improve logo processing

.github/labeler.yml
- ci: update labeler to auto-label Pull Requests
- added bonus: that might help provide code pointers in the future
=> ci: update labeler

.github/workflows/generate-docs.yml, README.md
Build redoc HTML page automatically and push it to Github Pages
=> doc: build openAPI documentation automatically

robotoff/metrics.py, robotoff/scheduler/__init__.py
Save number of insights, grouped by the following fields Every night at 1AM
=> feat: add insights metric

README.md
- doc: README refactor
- Added the Weekly meeting call
- Added contributors
- Added indicators
=> docs: README refactor

pyproject.toml
- fix: pyproject-fix
- Will the authors fix provoke any unintended side effects ?
=> fix: pyproject-fix

robotoff/cli/logos.py, robotoff/models.py, robotoff/prediction/types.py, robotoff/workers/tasks/import_image.py, scripts/insert_image_predictions.py, tests/integration/models_utils.py
- predictor for product_insight and prediction tables
- source_image and barcode for logo_annotation table
=> feat: add DB columns

doc/references/api.yml, robotoff/app/api.py, robotoff/app/core.py, tests/integration/models_utils.py, tests/integration/test_api.py
=> feat: allow users to filter by confidence in /questions

docker-compose.yml, robotoff/mongo.py
A few infrastructure-related fixes.
=> fix: Infra fixes

robotoff/scheduler/latent.py
Remove unused code that generated "latent" insights.
=> fix: remove legacy code

robotoff/insights/importer.py, robotoff/products.py, robotoff/scheduler/__init__.py, tests/unit/insights/test_importer.py
- check that source_image is valid
- use a different transaction to check insights and predictions
- check predictions before insights
Fixes #1087
=> fix: improve scheduled job refresh_insight

robotoff/app/api.py, robotoff/app/core.py, robotoff/insights/annotate.py, robotoff/off.py, robotoff/types.py, tests/integration/insights/test_process_insights.py, tests/integration/test_api.py
say when the edit was triggered by an anonymous vote
Fixes #1030
=> fix: improve Robotoff edit message

i18n/fr/LC_MESSAGES/robotoff.po
Fix a translation issue (also fixed in crowdin).
=> chore: fix translation on fr

.github/workflows/crowdin.yml
=> ci: better crowdin PRs

robotoff/cli/main.py, robotoff/cli/ocr.py, robotoff/prediction/ocr/dataclass.py
`initial_offset` was incorrect, as we added +1 to the offset even if no extra space was added at the end of the paragraph
=> fix: fix ocr word offset bug

Dockerfile, docker-compose.yml, robotoff/app/api.py, robotoff/prediction/ingredient_list/__init__.py, robotoff/prediction/ingredient_list/postprocess.py, robotoff/settings.py, robotoff/triton.py
Integrate NER ingredient detection model + add an API endpoint
=> feat: add first version of ingredient list NER + API

models/triton/ingredient-ner/config.pbtxt, robotoff/app/api.py, robotoff/prediction/ingredient_list/__init__.py, robotoff/prediction/ocr/core.py, robotoff/prediction/ocr/dataclass.py
- catch HTTP 404 error when fetching JSON from URL
- allow to specify model version for NER model
=> fix: improve ingredient detection pipeline

data/ocr/store_regex.txt
- Adding more international stores to the Stores regex
=> chore: Adding more international stores to the Stores regex

doc/references/api.yml, poetry.lock, pyproject.toml, robotoff/app/api.py, robotoff/app/core.py
- fix: add `insight_types` parameter in /question/{barcode}
- chore: upgrade transformers dependency
- fix: sort product questions by priority
=> fix: Improve question route

doc/references/api.yml, robotoff/app/schema.py, robotoff/prediction/category/neural/category_classifier.py, robotoff/prediction/category/neural/keras_category_classifier_3_0/__init__.py, robotoff/types.py, tests/conftest.py, tests/unit/insights/test_question.py, tests/unit/test_models.py, tests/unit/test_settings.py, tests/unit/test_slack.py
- allow to provide `image_embeddings` as input in `/predict/category`
- improve OpenAPI documentation
=> fix: Improve categorization api

poetry.lock, pyproject.toml, robotoff/prediction/object_detection/core.py, robotoff/settings.py, robotoff/utils/__init__.py, robotoff/utils/image.py, robotoff/utils/logger.py, robotoff/workers/tasks/import_image.py, tests/unit/utils/test_module.py
An error was raised for monochrome images (not RGB) See
https://openfoodfacts.sentry.io/issues/4166627511
Also add release info to sentry error tracking
=> fix: fix bug in run_upc_detection

doc/references/api.yml, robotoff/app/api.py, robotoff/app/core.py, tests/integration/test_core_integration.py
=> fix: replace parameter `country` by `countries`

data/category/neural/v3/image_embeddings_model_thresholds.json.gz, robotoff/insights/importer.py, robotoff/prediction/category/neural/category_classifier.py, robotoff/prediction/category/neural/keras_category_classifier_3_0/__init__.py
we have enough data if we wish to analyze it
=> fix: remove above-threshold-campaign

crowdin.yml
- #1164 
- Per: https://github.com/openfoodfacts/openfoodfacts-server/blob/main/crowdin.yml
=> ci: try to tweak Crowdin

.github/labeler.yml, data/ocr/store_regex.txt
- feat: add a few more stores for automatic extraction
=> feat: add a few more stores for automatic extraction

.github/workflows/top-issues.yml
=> ci: Fix top issues

data/ocr/store_regex.txt
- feat: Stores from across Europe
=> feat: Stores from across Europe

data/ocr/brand_taxonomy_blacklist.txt, robotoff/brands.py, robotoff/insights/importer.py, robotoff/products.py, robotoff/scheduler/__init__.py
- only exclude for 'taxonomy' predictor and not other predictors
- improve documentation in brand_taxonomy_blacklist.txt
- remove excluded brands once a day in scheduler
=> fix: improve brand exclusion for 'taxonomy' predictor

data/ocr/brand_taxonomy_blacklist.txt
=> fix: brand blocklist

robotoff/insights/importer.py, tests/unit/insights/test_importer.py
Predictions are very good:
https://hunger.openfoodfacts.org/questions?type=nutrition_image
=> feat: apply automatically nutrition images insights

robotoff/prediction/ocr/label.py, tests/unit/prediction/ocr/test_label.py
=> fix: fix wrong label rouge detection

robotoff/models.py
value should be null by default instead of being an empty list
=> fix: fix bounding box field default value

data/ocr/brand_logo_annotation.txt
- doc: little explainer for Google Cloud Vision
=> docs: little explainer for Google Cloud Vision

.github/workflows/container-deploy.yml
This change MongoDB connection for prod to reflect new instance, accessed via stunnel on ovh proxy.
**IMPORTANT:** only merge after migration happened.
=> chore: new mongodb connection through stunnel

FEATURES.md
- doc: Create FEATURES.md to doc features and todos
- Work in progress, but category regeneration and images are top of mind
=> docs: Create FEATURES.md to doc features and todos

docker/ml-gpu.yml, docker/monitor.yml
Fix the RESTART_POLICY for some containers that missed it: consequently, they were not restarted during machine reboot.
=> chore: Update docker config

Makefile, models/triton/nutrition-table-yolo/labels.txt, robotoff/cli/main.py, robotoff/insights/importer.py, robotoff/prediction/object_detection/core.py, robotoff/types.py, robotoff/workers/tasks/import_image.py
Change FasterRCNN model for nutrition detection by newly trained yolov8n.
=> feat: add Yolov8 model for nutrition table detection

poetry.lock, pyproject.toml, robotoff/app/api.py, robotoff/scheduler/__init__.py
- use UTC as timezone
- run update-insights at 3PM UTC instead of 9AM
=> fix: improve scheduler

robotoff/metrics.py
Add try / except so that a failure on one facet does not block every other facets.
=> fix: avoid failing all metrics for a single failure

.github/labeler.yml
- ci: Update labeler.yml to match other repos (same label names)
=> ci: Update labeler.yml to match other repos

.env, .github/workflows/container-deploy.yml, Makefile, docker-compose.yml, docker/prod.yml, robotoff/settings.py, scripts/backup_postgres.sh
and use `robotoff` DB instead of `postgres`
=> feat: switch from PostgreSQL 11 to PostgreSQL 16

robotoff/app/core.py
fixes #1147.
We now use a subquery instead of an outer join, which is much faster.
=> fix: use subquery when fetching questions without user votes

data/ocr/store_regex.txt
See this Slack thread: https://openfoodfacts.slack.com/archives/CF0286BRQ/p1723990343640559
Fixes #1394
=> fix: remove some store regex false positive

Makefile
Use v1.1 model:
https://huggingface.co/openfoodfacts/ingredient-detection
=> feat: update ingredient detection model

Makefile, docker/ml-gpu.yml, docker/ml.yml, robotoff/app/api.py, robotoff/prediction/image_classifier.py, robotoff/types.py
First model: the proof image classifier for Open Prices.
=> feat: Add image classifier models

doc/references/api.yml, robotoff/app/api.py, tests/unit/test_products.py
- update OpenAPI documentation
- add `order_by` param to GET /api/v1/insights route
=> docs: update doc

docker-compose.yml
See
https://github.com/openfoodfacts/.github/blob/main/docs/ports-and-project-names.md
@alexgarel @john-gom FYI
=> chore: use port numbers in Robotoff attributed range

robotoff/insights/annotate.py, robotoff/insights/importer.py, robotoff/prediction/nutrition_extraction.py, robotoff/products.py, tests/unit/insights/test_annotate.py, tests/unit/insights/test_importer.py, tests/unit/prediction/test_nutrition_extraction.py
- improve post-processing of nutrition extraction predictions
- improve import mechanism: detect better when insights should not be generated
- add more unit tests
=> fix: improve nutrition extraction

.github/labeler.yml
- ci: labeler for nutrition extraction
=> ci: labeler for nutrition extraction

doc/references/ingredients-spellcheck.md, tests/integration/models_utils.py
=> fix: failing code quality tests

robotoff/insights/annotate.py, robotoff/insights/importer.py, tests/integration/insights/test_annotate.py, tests/integration/insights/test_importer.py, tests/unit/insights/test_annotate.py, tests/unit/insights/test_importer.py
We now have 1 insight for each selected image to rotate.
=> fix: improve ImageOrientation importers and annotator

doc/references/predictions/image-orientation.md
=> docs: add for image orientation

robotoff/images.py, robotoff/insights/importer.py
- use `| None` notation for indicating Optional parameter
- remove legacy function that was unused
- improve slightly the documentation
- remove call to deprecated datetime.datetime.utcfromtimestamp
=> refactor: improve importer.py and images.py files

robotoff/cli/main.py, robotoff/insights/importer.py, robotoff/products.py, robotoff/utils/image.py, tests/unit/test_products.py, tests/unit/utils/test_image.py
- refactor: move convert_bounding_box_absolute_to_relative to utils.image
- refactor: transform Product.ingredients_text into a dict
- docs: improve docstring in importer.py
- fix: use the right Redis queue to publish events in create-redis-update
=> refactor: improve various modules

doc/references/predictions/ingredient-detection.md, robotoff/insights/importer.py, robotoff/types.py, robotoff/workers/tasks/import_image.py, tests/integration/models_utils.py, tests/integration/workers/tasks/test_import_image.py, tests/unit/insights/test_importer.py
Until now, the predictions of the nutrition detection model were only stored in the ImagePrediction table.
We now create predictions & insights based on those image predictions.
=> feat: add first implementation of ingredient_detection insights

doc/references/predictions/nutrient-extraction.md
- docs: road to api for nutrient extraction
=> docs: road to api for nutrient extraction

robotoff/batch/__init__.py, robotoff/cli/main.py, robotoff/products.py, robotoff/scheduler/__init__.py, robotoff/settings.py, robotoff/workers/tasks/__init__.py, tests/unit/pytest_utils.py, tests/unit/test_batch.py, tests/unit/workers/tasks/test_import_image.py
- download every night parquet files
- use the food parquet file as input for the spellcheck batch job
- correct incorrect naming for function parameter
- improve tests
=> refactor: improve spellcheck batch jobs

poetry.lock, pyproject.toml
=> chore(deps): update dependency

robotoff/workers/update_listener.py, tests/unit/workers/test_update_listener.py
And add unit tests for update listener service.
=> fix: discard redis events triggered by Robotoff actions

.github/workflows/api-lint.yml, .spectral.yml, Makefile, README.md
This is to maintain the correct structure of Spec file according to OSA rules and some better practices to generate good documentations.
=> feat: added spectral linting tool for OpenSpec Api file

doc/references/api.yml
Just updated the `api.yml` file and removed some of the error form the spec file and added good structure to it.
=> chore: updated the api.yml file and remove some erorrs and completed some incomplete routes

doc/references/api.yml
Signed-off-by: Jagjeevan Kashid <jagjeevandev97@gmail.com>
update the api.yml file and remove some errors and completed some incomplete routes
=> chore: Adding OperationId to specfile

doc/references/api.yml
I saw some wired problems in api doc generation so this PR fixes that issues.
=> chore: fixed some issue and not major things

.github/workflows/container-deploy.yml, docker-compose.yml, robotoff/notifier.py, robotoff/settings.py, tests/unit/test_notifier.py
Add a bearer token to the image moderation notifier
=> feat: add bearer token to nutripatrol auth

robotoff/scheduler/__init__.py
=> fix: clean old tmp directory in /tmp

.github/workflows/release-please.yml, release-please-config.json
after update to v4 of release please action.
=> chore: fix release please configuration

robotoff/workers/tasks/product_updated.py, tests/integration/workers/tasks/test_product_updated.py
=> fix: fix issue with subquery used in product_type_switched_job

doc/references/predictions/nutrient-extraction.md, robotoff/insights/importer.py, robotoff/prediction/ocr/product_weight.py, robotoff/utils/weight_unit.py, tests/unit/insights/test_importer.py, tests/unit/prediction/ocr/test_product_weight.py, tests/unit/utils/test_weight_unit.py
=> feat: improve nutrition insight generation

robotoff/workers/update_listener.py
=> fix: catch Redis events with empty codes

robotoff/health.py
=> fix: catch exceptions during healthcheck to return it in the response
