data/ocr/regex_stores.txt
Australian brand/store is known as 'Woolworths' (https://en.wikipedia.org/wiki/Woolworths_Supermarkets)
On deploy, probably need to do a migration of anything that ends back up in https://au.openfoodfacts.org/store/woolworth
=> Fix store name

data/ocr/store_regex.txt
Add Cora and Match as stores for Patrimoine Gourmand brand
=> Add Cora and Match as stores for Patrimoine Gourmand brand

doc/introduction/contributing.md, robotoff/ml/category/prediction_from_ocr/constants.py
The failing test is fixed by forcing the cli to read from a particular release, until we have a better story for how the models are released uniformly.
One of the questions I see is why we need this model for a unit test in the first place - ideally you would have a smaller, mock model in order to test the functionality of the predictor rather than using a heavy production model that needs to be fetched from somewhere.
=> Fix test_categories.py

doc/introduction/contributing.md
Add instructions to compile i18n, without which test_i18n.py fails on new repository.
=> Add last missing instruction needed for the test to run locally.

robotoff/cli/annotate.py, robotoff/cli/batch.py, robotoff/cli/spellcheck.py, robotoff/logos.py, robotoff/metrics.py, robotoff/off.py, robotoff/settings.py, robotoff/slack.py, robotoff/workers/tasks/update_recycle.py, tests/test_settings.py
Refactor the codebase to remove hardcoded URLs.
Since we are working on bringing up a 'dev' Robotoff server accessible via 'https://robotoff.openfoodfacts.net', we need to make the URLs used throughout the project more dynamic. To solve this, I am introducing a BaseURLProvider that can construct the desired URL on the fly, accounting for the Robotoff instance the code is currently running on.
=> Remove hardcoded domains

robotoff/logo_label_type.py, robotoff/logos.py, robotoff/settings.py, robotoff/slack.py, robotoff/workers/tasks/import_image.py, services/ann/settings.py, tests/test_settings.py, tests/test_slack.py
This PR achieves the following:
1. SLACK_TOKEN misconfiguration errors occur closer to init time, which helps to catch these misconfigurations sooner.
2. Slack functionality now uses the [factory design pattern](https://realpython.com/factory-method-python/), which allows to better encapsulate slack-only functionality and allows the caller not to care about checking for the currently running instance.
3. Adds tests for the new code (the old code didn't and still does not have test coverage - we can add it incrementally over time).
This is the last change necessary to allow running non-prod versions of Robotoff.
=> Allow to not post anything on Slack if the robotoff is running as dev/locally

robotoff/utils/__init__.py, services/ann/utils.py
by constructing the Image object directly from the response bytes rather than writing it to a temp file just to read it back into memory.
Not sure if this fixes the root cause of the linked issue. If this doesn't resolve it, at least we would get different errors in Sentry than `cannot identify image file '/tmp/tmpixa936_c'` so it's still a step in the right direction.
=> Optimise image cropping

robotoff/app/api.py, robotoff/app/core.py
Currently many of the API calls will always append 'where latent=false and annotated=false' to the Postgres query because the defaults for these func params are `False` instead of `None`.
This causes missing data to be returned in the API calls. This PR fixes this
=> Fix incorrect peewee query

Dockerfile
Works locally on my machine - previously using 1.1.8 poetry caused issues on the server, but pinning poetry to 1.1.7 causes missing poetry dependencies at run time.
=> Use the latest poetry version and invoke gunicorn through it

robotoff/insights/dataclass.py, robotoff/insights/importer.py, tests/insights/test_importer.py
- Restore automatic processing for `product_weight`, `expiration_date` insight types
- Add very basic tests for product insight import as a starter
=> Add first tests for importer.py and fix automatic processing bug

robotoff/insights/ocr/core.py
Robotoff breaks in the dev environment as this model has not been fully integrated and is crashing the Robotoff workers. Temporarily removing the code to allow Robotoff to run in dev.
=> Temporarily remove OCR ML category detection as it breaks Robotoff

.env, .github/workflows/container-deploy.yml, Dockerfile, docker-compose.yml, docker/monitor.yml, statsd.conf
Adds a `statsd-exporter` sidecar container that will collect metrics from `gunicorn`, to be scraped by Prometheus.
=> feat: add monitoring config w/ gunicorn statsd

docker/ml.yml
Updating TF Serving to `2.4.0` as the older versions don't support the preprocessing layers in the category classifier.
=> Bump TF Serving Version

robotoff/utils/es.py
Turns out you still need to specify the doctype in ES [insert requests](https://elasticsearch-py.readthedocs.io/en/v7.15.2/api.html#elasticsearch.Elasticsearch.bulk) even if it's the default type.
=> Add the default doc type to ES requests

robotoff/elasticsearch/category/match.py, robotoff/elasticsearch/export.py, robotoff/elasticsearch/index/category_index.json, robotoff/elasticsearch/index/product_index.json, robotoff/settings.py, robotoff/utils/es.py
In #478 I removed the doc_type parameters as they were supposedly not needed in later ES versions.
However, even with the default `_doc`, we have to provide the document type when making requests.
Since we need to provide it anyway, I've reverted `_doc` to `document` as keeping it as `_doc` would require a prod migration. As we're trying to migrate prod to a new set-up, any additional complexities are better avoided at this point
=> Re-introduce DOCTYPE for Elasticsearch queries

robotoff/products.py
Based on the slack discussion:
`shutil.move` throws a `Invalid cross-device link:` when moving files from /tmp/ to /opt/robotoff/.. This is most likely a result of shutil.move optimisations.
Instead of moving the file in one step, we can bypass the issue with an explicit `copy` followed by a `remove` operation.
In this case, an explicit `remove` is not necessary as cleanup will happen when we exist the `with ....` branch.
=> Replace moving of the PO dump from /tmp with copy

.github/workflows/autoblack.yml, .pre-commit-config.yaml, Dockerfile, mypy.ini, poetry.lock, pyproject.toml, robotoff/off.py, robotoff/settings.py
Various linting fixes and improvements:
- Use the same black version in CI autoblack and in pyproject.yml
- Update linter versions in pre-commit config
- Install mypy stub packages when launching mypy on CI
- Move mypy config to pyproject.toml
=> Mypy black updates

robotoff/insights/importer.py, robotoff/prediction/category/neural/category_classifier.py, tests/integration/insights/test_category_import.py, tests/unit/cli/test_main.py, tests/unit/prediction/category/neural/test_category_classifier.py
This is a fix to avoid predicting categories when we should not.
@mithridatea you need to confirm my choice that we should not predict with neural if ingredients is empty (I may be wrong).
=> fix: straight conditions for category insights

robotoff/elasticsearch/export.py, robotoff/insights/importer.py, robotoff/models.py
As we further decouple prediction from insight import, we need to keep
track if the prediction automatic_processing is null or not.
=> Make `prediction.automatic_processing` field nullable

robotoff/scheduler/__init__.py, robotoff/workers/tasks/__init__.py, robotoff/workers/tasks/import_image.py
I prefer to have a global transaction for each task, as it make code more robust.
We had a problem in preprod, because of a constraint change in table due to #592 which needed a transaction but it was not spotted, and there was some task where no transaction was invoked, resulting in all tasks failing thereafter… see [sentry 2969916843](https://sentry.io/organizations/openfoodfacts/issues/2969916843/?environment=dev&project=1415205&query=is%3Aunresolved)
I think it's safer to put it at a high level.
=> Ag fix scheduler and tasks transaction - fixes #608

.github/workflows/release-please.yml
because github actions do not trigger actions by default
=> ops: use a specific token for release please

.github/workflows/pull_request.yml, data/ocr/packaging.txt, tests/unit/prediction/ocr/test_packaging.py
- Brute-force extend the number of French recycling instructions we can extract based on CITEO guidelines
- #600
=> Packaging Flashtext extension

docker/dev.yml, robotoff/models.py, tests/conftest.py, tests/integration/test_api.py, tests/integration/test_models_integration.py
fix: vote should cascade on insight removal fixes #619
you must run migration manually:
```
ALTER TABLE annotation_vote DROP  CONSTRAINT annotation_vote_insight_id_fkey;
ALTER TABLE annotation_vote ADD CONSTRAINT annotation_vote_insight_id_fkey FOREIGN KEY (insight_id) REFERENCES product_insight(id) ON DELETE CASCADE;
```
- #619
=> Ag fix vote on delete

robotoff/app/api.py, robotoff/workers/listener.py, robotoff/workers/tasks/product_updated.py
Avoid having a worker stalled for x seconds. Important in case of massive updates
**Note**: I need this before #636
=> feat: sleep now happens in thread

robotoff/app/api.py, robotoff/app/core.py
This modification is proposed to provide more flexibility in question fetching especially for hunger-game
We were relying on the randomness of question requests to populate the batch of questions. But now, you can run multiple time the random query and get the same list of questions
https://robotoff.openfoodfacts.org/api/v1/questions/random?count=10&lang=fr&insight_types=category&value_tag=en:teas
My assumption is that if no product has obtained a vote, `random() * nb_votes` is always 0 and so the order is the "natural" one in the database.
I also reused codes from insight API request to add `page` parameter to the questions route such that event with `popular` soring we are able to fetch all the data
https://github.com/openfoodfacts/openfoodfacts-hungergames/issues/394
=> fix(api): Question API, fix query randomness, and allow to use pagination

.gitattributes
People using windows needs not have git convert `lf` to `crlf` as git normally does because files are meant to run in docker, which is a linux environment (so we need `lf`).
=> ops: add gitattributes for windows

.github/workflows/container-deploy.yml, robotoff/taxonomy.py
Taxonomy download do not check returned status code, which leads to inconsistent error messages.
=> fix: fix taxo dl net

tests/integration/insights/test_process_insights.py, tests/integration/models_utils.py, tests/integration/test_scheduler.py
We were sometime using `utcnow`  and sometime `now`  which makes tests fails in certain conditions
=> fix: fix tests date to use utc

.env, .github/workflows/autoblack.yml, .github/workflows/container-deploy.yml, poetry.lock, pyproject.toml, robotoff/app/api.py, robotoff/app/core.py, robotoff/app/events.py, robotoff/settings.py, tests/integration/test_api.py
see https://github.com/openfoodfacts/openfoodfacts-events
Replaces #674
Call openfoodfacts-events each time a user annotate an item
=> feat: add events API requests

.github/workflows/github-projects.yml
- ci: don't run on dependabot made prs as it will fail
=> ops: don't run on dependabot made prs as it will fail

Makefile, doc/how-to-guides/test-and-debug.md
=> feat: isolate test network + make single test run

doc/introduction/contributing.md
mkdocs can't reference external files
This should repair action of doc generation and deployment.
fixes #808
=> doc: fix links

robotoff/app/api.py, robotoff/app/core.py, tests/integration/test_api.py, tests/integration/test_core_integration.py
This PR does the following [from here](https://github.com/openfoodfacts/robotoff/issues/618#issuecomment-1231879826): 
> Next is LogoAnnotationCollection
>
> It's the same thing, with as previous view but for LogoAnnotation:
filters on:
>
> 
> 
> - barcode
> - type filter (a list of type) keep_types (filter on annotation_type)
> - value_tag (filter on annotation_value_tag)
- #618
=> feat: Get Logo Annotation list 

robotoff/app/core.py, tests/integration/test_api.py
- The instruction of the PR is [here](https://github.com/openfoodfacts/robotoff/issues/618#issuecomment-1235475222): 
>by default, always sort on freshest item (higher id ?) first
- #618
=> feat: Sort collection API

.github/workflows/container-deploy.yml, doc/introduction/notifications.md, robotoff/settings.py, robotoff/slack.py, tests/unit/test_slack.py
Send flagged images to an external moderation database.
Replaces #862
=> feat: Add image moderation service

doc/references/api.md, robotoff/app/api.py, tests/integration/test_api.py
Added documentation for the following APIs:
1. `/api/v1/predictions/`  PredictionCollection()
2. `/api/v1/images/prediction/collection`  ImagePredictionCollection()
3. `/api/v1/images` ImageCollection
4. `/api/v1/annotation/collection` LogoAnnotationCollection
5. `/api/v1/questions/unanswered/` UnansweredQuestionCollection
- #618 
- #896
=> doc: Added documentation for 5 Collection APIs

robotoff/elasticsearch/category/predict.py, robotoff/prediction/category/neural/category_classifier.py, tests/integration/insights/test_category_import.py, tests/unit/prediction/category/neural/test_category_classifier.py, tests/unit/workers/tasks/test_product_updated.py
data->model is a deprecated field, all predictor version/type must be stored in the predictor field
=> fix: store category neural model in ProductInsight.predictor field

doc/how-to-guides/deployment/dev-install.md, docker/dev.yml, docker/mongodb.yml
To avoid conflicts with Product Opener docker mongo instance in dev mode
=> fix: move docker mongodb service to a distinct file in dev mode

.env, docker/dev.yml, robotoff/off.py, robotoff/scheduler/__init__.py, robotoff/settings.py
- make some part of the code and settings more compliant to a use with a local deploy of product opener
- settings had a dangerous pattern in the object to get domains, fixed it.
- also made scheduler more resilient to not having network 
Note: a more serious refactor of networks between docker should be done, but later...
This was done to be able to test https://github.com/openfoodfacts/openfoodfacts-server/pull/7379
=> refactor: robustness and localdev

robotoff/prediction/ocr/packager_code.py, tests/unit/prediction/ocr/test_packager_code.py
There are many false positives during USDA packager code extraction currently, we disable the extraction until the issue is fixed.
=> fix: temporarily disable USDA packager code extraction

data/ocr/label_logo_annotation.txt, data/ocr/label_whitelist.txt, robotoff/insights/question.py, robotoff/prediction/ocr/label.py, tests/integration/models_utils.py, tests/unit/prediction/ocr/test_label.py
fr:ab-agriculture-biologique is the correct version
A DB fix in preprod and production is necessary too.
Fixes #450
=> fix: replace with fr prefix references to en:ab-agriculture-biologique

robotoff/insights/annotate.py
No need to save it if the provided data was invalid or if it's just a vote
=> fix: only save annotation_result in ProductInsight when needed

doc/references/api.yml, robotoff/app/api.py, robotoff/app/schema.py, robotoff/prediction/category/neural/category_classifier.py
- feat: add a `threshold` parameter to /predict/category endpoint
- feat: Improve /predict/category endpoint (allow to provide model input instead of only fetching the product from
DB)
- doc: document /predict/category endpoint on OpenAPI
=> feat: Improve predict category endpoint

.github/workflows/generate-docs.yml, mkdocs.yml
Default link is wrong, see https://openfoodfacts.github.io/robotoff/ (pen on right top corner).
I did configure it on openfoodfacts-server, so I knew how to fix :-)
Also run the documentation build (without publishing) when we touch the doc to avoid breaking it by inadvertence.
=> doc: fix edit link on mkdocs docs

README.md, doc/references/api.yml, robotoff/app/api.py
- fix: create new /images/logos/search endpoint from /images/logos
- fix: allow to fetch both annotated/not annotated logos in /images/logos/search
- doc: add link to rendered view of API documentation in README.md
Required for https://github.com/openfoodfacts/hunger-games/issues/262
=> fix: improve /images/logos endpoint

doc/research/logo-detection/benchmark.md
* Add doc and results of the embeddings models benchmark computed to mesure the efficiency of each model through their ability to predict the right label for every logo.
=> doc: adding results of the classifier benchmark to the doc

robotoff/cli/main.py, robotoff/insights/importer.py, robotoff/models.py, robotoff/prediction/ocr/category.py, robotoff/products.py, tests/integration/insights/test_category_import.py, tests/integration/models_utils.py, tests/unit/insights/test_importer.py
The main addition of this PR is a fix of the insight import mecanism.
Currently, when a prediction based on a more recent image is available, we don't transform this prediction into an insight, we keep the old insight.
This is problematic as the insight based on the newer image may make it automatically processable (if the image is selected or if it's not too old compared to most recent images). As knowing which insight to keep/delete and which candidate to import is tricky (many subtle bugs were discovered since the introduction of this feature), I chose here a more radical approach: we regenerate all insights for a product from predictions and only keep annotated insights in DB.
I also added a better sorting of candidates:
- we now set a higher priority on candidates that are …
=> fix: fix insight import mecanism

data/ocr/brand_taxonomy_blacklist.txt, doc/references/api.yml, robotoff/app/api.py, robotoff/app/core.py, robotoff/insights/importer.py, robotoff/models.py, scripts/ocr/dump_ocr.py, tests/unit/insights/test_importer.py
A bunch of various fixes/features:
- fix: always serialize insights the same way
- fix: fix min_confidence parameter in /logos/search route
- fix: add a small fix on dump_ocr.py
- fix: make API parameters uniform
- feat: allow to filter insights/question by predictor value
- fix: update brand taxonomy blacklist
- feat: set value_tag to canonical label value during prediction import
- fix: fix refresh_all_insights function
=> fix: add small fixes

robotoff/app/core.py, tests/integration/test_api.py
So that this mechanism does not have to be implemented client-side.
The voting mechanism has also been updated: before, all classes
(0, 1, -1) could be considered a valid value. Now, -1 is exclusively
used for users to ignore insights, so it's not considered when
computing vote counts (only 0 and 1 are considered).
Another bug was fixed: when vote counts for 0 and 1 are both >= 2,
we save the insight as invalid (-1) instead of saving it as negative
(0).
Solves #908
=> fix: fix skip mechanism

robotoff/cli/insights.py, robotoff/cli/main.py, robotoff/insights/extraction.py, robotoff/insights/importer.py, robotoff/logos.py, robotoff/scheduler/__init__.py, robotoff/workers/tasks/import_image.py, robotoff/workers/tasks/product_updated.py, tests/integration/insights/test_category_import.py, tests/unit/insights/test_importer.py, tests/unit/workers/tasks/test_product_updated.py
Make voting system work again, and avoid the deletion/creation of insights when there are only minor updates.
Also delete the legacy `automatic` parameter in InsightImporter.
Fixes #975
=> fix: fix insight import (again!)

robotoff/app/schema.py
value shouldn't be required (ex: type=no_logo)
=> fix: fix UPDATE_LOGO_SCHEMA JSON schema

robotoff/workers/tasks/import_image.py
Nutrition table detection is not used at the moment, and every new image is costly in CPU (as we perform object detection).
Disable it until we either need it or get a GPU server.
=> fix: disable nutrition table detection

robotoff/workers/tasks/import_image.py
- Adding manual resizing with PIL library.
- [CLIP processor]() was used as [the only processing step for logos](https://github.com/openfoodfacts/robotoff/blob/master/robotoff/triton.py#L23). However, to fit the size (224,224) expected by CLIP, it resizes only the smallest dimension of the image and then crops the logo. We don't want to loose data by cropping.
=> fix: manually cropping and resizing of logos before CLIP processor

.github/workflows/container-deploy.yml
We moved mongodb to a temporary server to be able to upgrade our servers.
=> ci: mongodb migration to off3

.github/workflows/pull_request.yml, robotoff/metrics.py
Fix long-standing failure in unit test & check GitHub action.
This issue arose a few months ago, probably after a change on Github side. The issue comes from permission issues on shared (mounted) folders between the host and the docker container: the process doesn't have write access on these shared folders, which is necessary to:
- compile i18n .po files (it was done before launching tests)
- write coverage reports in .cov folder
I didn't manage to solve the permission issue, but found a workaround:
- don't compile the po files before launching tests, as we already do that in Dockerfile
- run unit and integration tests inside the container as root user
This solution is not perfect (as we should avoid running processes as root), but it only affects GitHub actions.
=> chore: fix unit test action failure

robotoff/insights/normalize.py, robotoff/prediction/category/matcher.py, robotoff/prediction/category/neural/keras_category_classifier_3_0/__init__.py, robotoff/prediction/ocr/brand.py, robotoff/prediction/ocr/category.py, robotoff/prediction/ocr/dataclass.py, robotoff/prediction/ocr/expiration_date.py, robotoff/prediction/ocr/grammar.py, robotoff/prediction/ocr/label.py, robotoff/prediction/ocr/location.py, robotoff/prediction/ocr/nutrient.py, robotoff/prediction/ocr/packager_code.py, robotoff/prediction/ocr/product_weight.py, robotoff/prediction/ocr/store.py, robotoff/prediction/ocr/trace.py, robotoff/utils/fold_to_ascii.py, robotoff/utils/text.py, scripts/ocr/extract_ocr_text.py, tests/unit/prediction/ocr/test_dataclass.py, tests/unit/prediction/ocr/test_location.py
There was quite a bit of refactoring to allow this feature, that will allow us:
- to have a bounding box of the words for every regex/flashtext detection
- to detect ingredients on photos, which is the first step to be able to compute an ingredient list photo crop automatically
=> feat: allow to know where regex-based detections are located in the image

doc/references/api.yml, robotoff/app/api.py, robotoff/app/core.py, tests/integration/test_api.py
- limit and offset parameters were not used
- /images/predictions/collection and /images/predictions were providing the same functionality: merge them under /image_predictions route
- add these two endpoints to OpenAPI documentation
- rename `/api/v1/images/predictions/import` into `/api/v1/image_predictions/import`
=> feat: fix image prediction and prediction endpoints

robotoff/products.py, robotoff/scheduler/__init__.py, robotoff/taxonomy.py, robotoff/utils/i18n.py, scripts/clean_insights.py, tests/unit/prediction/ocr/test_brand.py, tests/unit/prediction/ocr/test_store.py
- loading min dataset in memory took +20GB of RAM, which made the
scheduler crash. By allowing a projection (selected fields) to be passed
as parameter, we reduce memory usage to ~2GB.
- Use ServerSide cursor to avoid excessive memory consumption
- Also delete predictions associated with deleted products
fixes #958
We still need to check that the image has not been deleted.
=> fix: Fix refresh insight scheduler

README.md
Description:  This pull request fixes an incorrect link in the README.md file, updating it to the correct one.
Changes
- Updated the incorrect link in the README.md file from https://openfoodfacts.github.io/robotoff/robotoff/explanations/predictions/ to https://openfoodfacts.github.io/robotoff/explanations/predictions/.
Related issue:
- Fixes #[1096]
There is an incorrect link in the README.md file. The link needs to be updated to the correct one. This issue falls under the "docs" category according to the [Commitizen Conventional Commit Types](https://github.com/commitizen/conventional-commit-types/blob/master/index.json).
- ISSUE: #1096
=> docs: incorrect link in README.md predictions section

Makefile, doc/introduction/architecture.md, docker-compose.yml, docker/dev.yml, robotoff/app/api.py, robotoff/cli/main.py, robotoff/settings.py, robotoff/types.py, robotoff/workers/queues.py, robotoff/workers/tasks/import_image.py, tests/unit/workers/test_queues.py
We create as many high priority queue as they are workers, and assign each worker (whether high or low priority) to a unique queue. This way, we reduce the risk of concurrent DB write for the same product.
Also, send webhook update jobs for all projects, as we now have a MongoDB connection for all projects.
=> fix: always use the same queue for jobs of the same product

robotoff/insights/importer.py, robotoff/redis.py
See https://openfoodfacts.sentry.io/issues/4114245248/?alert_rule_id=662444&alert_timestamp=1682067470955&alert_type=email&environment=prod&project=1415205&referrer=alert_email
Job took 2 minutes, and the lock expires after 1 min. We shouldn't throw an error when trying to release a lock that expired.
=> fix: fix error raised when releasing expired lock

Makefile, docker-compose.yml, docker/prod.yml, scripts/backup_postgres.sh
Adding automatic backup of PostgreSQL database.
Backups are stored in a new ZFS dataset (`/rpool/backups/robotoff`) on OVH3.
~Backup is performed automatically every night at 0:05 using Github Actions.~
edit: the command timeout when launched through Github Action (`make backup_postgres`, but not when launched locally.
We will use either crontab or systemd timers to launche it everyday.
=> chore: adding automatic backup of PostgreSQL database

poetry.lock, pyproject.toml, robotoff/insights/importer.py, robotoff/off.py, robotoff/prediction/category/neural/keras_category_classifier_3_0/preprocessing.py, robotoff/taxonomy.py, scripts/category_dataset.py, tests/conftest.py, tests/integration/test_annotate_image.py, tests/unit/insights/test_question.py, tests/unit/test_taxonomy.py
Use OFF SDK to replace part of Robotoff codebase.
=> refactor: add off sdk

robotoff/app/api.py
Disallow completely indexation: otherwise, web crawlers send millions of requests to Robotoff (420k requests/day by Google alone)
=> fix: add robots.txt

Makefile, doc/explanations/category-prediction.md, doc/introduction/architecture.md, robotoff/app/api.py, robotoff/cli/main.py, robotoff/prediction/category/matcher.py, robotoff/scheduler/__init__.py, robotoff/workers/main.py, robotoff/workers/tasks/product_updated.py, tests/unit/workers/tasks/test_product_updated.py
Disable matcher predictor for category, as categorization errors mostly come from the matcher predictor on Hunger Games, and as the neural categorizer almost always returns more accurate predictions for products for which the matcher predictor fails.
We keep the predictor available through the API, but don't use it when products are updated.
=> feat: Remove matcher predictor

poetry.lock, pyproject.toml, robotoff/images.py, robotoff/models.py, robotoff/workers/tasks/import_image.py, tests/unit/test_images.py
Used for near-duplicate image detection.
It's a first step to solve https://github.com/openfoodfacts/robotoff/issues/1271
=> feat: store fingerprint of all images

robotoff/cli/main.py, robotoff/settings.py, scripts/category_dataset.py
- reduce number of k nearest neighbors to consider to 10 (instead of 100). We have a much better annotation coverage as at the beginning of the project, and 100 generates too many false positive, and prevent a correct brand logo detection.
- improve logo DB update CLI command
=> fix: logo improvements

.github/workflows/container-deploy.yml, Dockerfile, Makefile, docker-compose.yml, docker/dev.yml, gunicorn.py, migrations/001_initial.py, migrations/002_add_bounding_box.py, poetry.lock, pyproject.toml, robotoff/cli/main.py, robotoff/insights/importer.py, robotoff/models.py, robotoff/settings.py, tests/integration/models_utils.py
- add migrate_peewee library to handle DB migrations
- try with a new `product_insight.bounding_box` field
=> feat: add DB migration library

.github/workflows/container-deploy.yml
We now apply migrations before starting the new version. Most of the time it's not an issue, and it prevents downtimes.
=> fix: fix migration application during deployment

robotoff/app/api.py, robotoff/images.py, robotoff/workers/tasks/product_updated.py, tests/integration/test_images.py
We just kept everything in DB unmodified (image, prediction, insight)
=> fix: mark images as deleted in DB when deleted on Product Opener

.gitignore, poetry.lock, pyproject.toml, robotoff/app/api.py, robotoff/images.py, robotoff/prediction/category/neural/keras_category_classifier_3_0/__init__.py, robotoff/prediction/ocr/location.py, robotoff/prediction/ocr/packager_code.py, robotoff/prediction/ocr/trace.py, robotoff/settings.py, robotoff/utils/cache.py, robotoff/utils/image.py, robotoff/workers/tasks/import_image.py, tests/unit/prediction/ocr/test_location.py, tests/unit/test_cache.py, tests/unit/utils/test_image.py
This PR includes several commits that add a disk cache mechanism to cache images, remove the CachedStore class, and add tests for _get_image_from_url.
=> feat: improve caching mechanism

data/ocr/store_regex.txt
=> fix: more stores

Dockerfile, doc/references/api.yml, docker-compose.yml, robotoff/app/api.py, robotoff/app/core.py, robotoff/images.py, robotoff/logos.py, tests/integration/test_images.py, tests/unit/test_logos.py
- don't include logos from deleted images in API routes (when it makes sense not to return them)
- delete logo embeddings (from ES and in DB), logos and image predictions of deleted images
- improve documentation
=> fix: logos improvements

Makefile, docker-compose.yml, docker/dev.yml, robotoff/cli/main.py, robotoff/insights/extraction.py, robotoff/prediction/category/__init__.py, robotoff/prediction/category/neural/category_classifier.py, robotoff/prediction/category/neural/keras_category_classifier_3_0/__init__.py, robotoff/prediction/ingredient_list/__init__.py, robotoff/prediction/object_detection/core.py, robotoff/triton.py, robotoff/workers/tasks/import_image.py, robotoff/workers/tasks/product_updated.py, tests/integration/insights/test_extraction.py, tests/integration/test_import_image.py, tests/integration/workers/tasks/test_import_image.py, tests/unit/elasticsearch/test_export.py
- allow to run inference on a distinct Triton server
- improve worker task dispatch
- add a new CLI command to run category detection on the full DB
=> feat: add multiple triton backend

.github/workflows/container-deploy.yml, robotoff/notifier.py
+ add a log message in notify_image_flag method
=> fix: fix nutripatrol deployment

robotoff/app/api.py, robotoff/notifier.py, tests/unit/test_notifier.py
- don't publish anymore on Slack public channel
- specify the reason when pushing to nutripatrol
- remove the likelihood key
=> feat: improve Slack & nutripatrol notifier

robotoff/insights/annotate.py
Following this bug report on Slack: https://openfoodfacts.slack.com/archives/CF0286BRQ/p1718194556411239?thread_ts=1718190525.623749&cid=CF0286BRQ
=> fix: don't select nutrition image if one has already been selected

data/ocr/store_regex.txt
Added norwegian stores: 
- Coop Obs and Coop Extra (Also often written as only “Obs” or "Extra", but part of "Coop Norge", a Norwegian cooperative)
- KIWI
- Bunnpris
- Meny
- Joker
- Spar (This chain is all over Europe as far as I know) 
- Narvesen (national kiosk chain)
=> chore: Update store_regex.txt

.env, .github/workflows/container-deploy.yml, docker-compose.yml
Following the suboptimal config of off-query:  https://github.com/openfoodfacts/openfoodfacts-query/issues/48
Our cache-hit for share buffers is currently 60%, while it should ideally be >90% (https://easyteam.fr/postgresql-tout-savoir-sur-le-shared_buffer/)
=> chore: increase SHARED_BUFFERS and WORK_MEM

Makefile, migrations/004_drop_indices.py, robotoff/app/api.py, robotoff/models.py
Drop unused indices:
- logo_annotation_nearest_neighbors (8447 MB in prod)
- image_prediction_data (unused, 3286 MB in prod)
- product_insight_data (almost unused, 3047 MB in prod)
- product_insight_predictor_version (unused, 517 MB in prod)
- logo_annotation_bounding_box (unused, 1633 MB in prod)
- image_prediction_max_confidence (useless, 280 MB in prod)
- image_width (unused, 324 MB in prod)
- image_height (unused, 310 MB in prod)
The `logo_annotation_nearest_neighbors` index currently (as of 2024-07-11) takes 8447 MB of space in production, just so that we can once in a while get logo annotations without nearest neighbors (nearest_neighbors is NULL).
Solves partially #572.
Some SQL queries need to be rewritten before deleting other indices on product_insight or prediction table.
=> fix: drop unused indices

robotoff/app/api.py, robotoff/app/core.py
The query was really slow, as we needed a seqscan to know the exact count of insights following the criteria, including the vote criterion.
The count could be really high (ex: on https://hunger.openfoodfacts.org/questions we have 1.5M insights).
By limiting to 100, we dramatically reduce query performance.
Related to #1147
=> fix: improve question count query performance with vote

migrations/007_add_logo_annotation_server_type_index.py, robotoff/app/api.py, robotoff/cli/main.py
Fixes #1386.
We use the newly indexed column `logo_annotation.server_type` to filter logos of a specific `server_type`.
Note that the sampling fraction we've chosen (20%) may not be adapted depending on how infrequent a certain `server_type` is. Currently, we only have logos with `server_type=off`, so we can keep it this way.
=> fix: Improve perf random logo search

Makefile
It appeared the po-default network creation comes too late in the make dev pipeline, leading to an error with init-elasticsearch. Create po-default network is added at the beginning of the pipeline instead..
```bash
~/projects/openfoodfacts/robotoff main !20 ❯ make dev                                                                                                      Py base
🥫 Welcome to the Robotoff dev environment setup!
🥫 Note that the first installation might take a while to run, depending on your machine specs.
🥫 Typical installation time on 8GB RAM, 4-core CPU, and decent network bandwith is about 2 min.
🥫 Thanks for contributing to Robotoff!
docker compose --env-file=.env build api 2>&1
[+] Building 200.6s (32/32) FINISHED …
```
=> fix(dev_build): :zap: Add network po-default before build in make dev

robotoff/prediction/ocr/product_weight.py, tests/unit/prediction/ocr/test_product_weight.py
fixes https://github.com/openfoodfacts/robotoff/issues/1398
=> fix: fix product weight detection bug

robotoff/prediction/ingredient_list/__init__.py, robotoff/prediction/ingredient_list/transformers_pipeline.py
It looks like it’s because we’re using the “FIRST” aggregation strategy, with a tokenizer that is not word-aware: we’re falling back to some heuristics (the presence of spaces before/after the word), that somehow fails here.
Indeed, XLM-RoBERTa model does not use the same tokenizer as RoBERTa, and uses an Unigram model (instead of BPE), which is not word-aware.
Another issue of the “FIRST” aggregation strategy is that the ending dot after the ingredient list is predicted as part of the ingredient list, even though it’s not in the non-aggregated prediction. By switching to “SIMPLE” strategy (a strategy without an error correction mechanism), we don’t have this issue anymore, but two subwords belonging to the same word are sometimes predicted as belonging to two entities.
A more in-depth …
=> fix: fix entity aggregation bug for NER detection

robotoff/cli/main.py, robotoff/off.py
Add a script to normalize all barcode and image paths according to the following normalization rules:
https://github.com/openfoodfacts/openfoodfacts-server/blob/ac9e33e9d31d0a080335aa1e8dfd91cacfec4c3f/docs/api/ref-barcode-normalization.md
=> fix: add script to normalize barcodes in DB

doc/references/api.yml, robotoff/insights/annotate.py, tests/integration/insights/test_annotate.py
Add Ingredients Spellcheck contributor annotation to `insight/annotate` route.
Now, the contributor can either validate or modify the model correction .
This modification is later added to `insights.data` in addition to be updated in the database.
- Spellcheck
=> feat: Spellcheck annotate

robotoff/metrics.py
=> fix: fix wrong call to logger.exception

robotoff/insights/importer.py
some products have an empty "images.nutrition" dict we check here that imgid key exists in the image data
fixes #1442
=> fix: fix KeyError exception in UPCImageImporter

robotoff/prediction/nutrition_extraction.py
=> fix: convert image to RGB before nutrition extraction

robotoff/notifier.py, tests/unit/test_notifier.py
- don't send beauty events to nutripatrol
- send real text comment to Nutripatrol
- stop sending moderation notifications to Slack
=> feat: improve Slack & nutripatrol notifiers

robotoff/insights/importer.py, tests/unit/insights/test_importer.py
We check that the brand was in the EAN barcode ranges for every brand prediction. However, it lead to too many false rejection. We now only check barcode range and brand blacklist for brands have the 'taxonomy' or 'curated-list' predictor.
=> fix: fix barcode filtering

robotoff/scheduler/__init__.py
A return statement was missing, and Parquet file was pushed in staging as well
=> fix: fix Parquet dataset push to Hub

docker-compose.yml
the scheduler crashes when Parquet export is done
=> chore: increase memory limit for scheduler

gunicorn.py
This is done to limit the effect of asset caching or of possible memory leaks on the RAM consumption on gunicorn workers.
=> fix: restart gunicorn workers every 50 requests

doc/references/api.yml, robotoff/app/api.py
Add a new `campaigns` filter to /api/v1/insights route.
=> fix: allow to filter insights by campaign

robotoff/app/api.py, robotoff/app/core.py
We can then support "skip" votes on the nutrition game (https://hunger.openfoodfacts.org/nutrition)
=> fix: support votes on GET /api/v1/insights route

doc/references/api.yml, robotoff/app/api.py, robotoff/app/core.py
- don't perform a join by default with logo_annotation table when calling the endpoint.
- allow to filter by image_id in /api/v1/image_predictions
=> feat: improve /image_predictions route

docker/ml-gpu.yml, docker/ml.yml, robotoff/cli/main.py, robotoff/prediction/nutrition_extraction.py
Use the new model (triton version `2`)
=> feat: Upgrade nutrition extractor model

robotoff/workers/queues.py, robotoff/workers/update_listener.py
When there is a massive update on the Open Food Facts server, put them in lower priority queues, to keep user submissions in high priorities, and be able to ask them question quickly.
fixes: #1519
=> feat: low queue for mass updates

robotoff/images.py, robotoff/types.py, robotoff/workers/tasks/product_updated.py
**Signed-off-by:** Areeb Ahmed ([areebshariff@acm.org](mailto:areebshariff@acm.org))
- Fix `ValueError` in `update_insights_job` by validating empty barcodes  
- Add barcode validation in `delete_images` to handle deleted products
Closes #1445
=> fix: add barcode validation to image deletion and product update processes

README.md
Reason for change:
The original sentence was somewhat unclear and internally inconsistent — it treated "updates," "insights," and "predictions" as if they were all on the same level, but later implied that predictions are combined to form insights. After reviewing the flow of how Robotoff works, I reworded the description to better reflect its role in managing the full process from predictions to user-reviewed updates. Explanation based on the Predictions and Insights docs (https://openfoodfacts.github.io/robotoff/explanations/predictions/)
- Updated the first paragraph of the README.md file
- Clarified the relationships between predictions, insights, and updates
Not applicable — documentation only (Markdown text edit)
None
Minor documentation improvements (no issue filed yet)
=> docs: clarify Robotoff intro paragraph in README

.pre-commit-config.yaml, legacy/ocr_category/prediction_from_ocr/__init__.py, legacy/ocr_category/prediction_from_ocr/cleaner.py, migrations/003_add_logo_text_field.py, migrations/004_drop_indices.py, pyproject.toml, robotoff/off.py, robotoff/prediction/ocr/core.py, robotoff/workers/queues.py, tests/conftest.py
- Wrapped long docstring lines to comply with flake8 W505 (max-line-length=88).
- Added missing whitespace around arithmetic operator to fix flake8 E226.
- Files updated:
- legacy/ocr_category/prediction_from_ocr/__init__.py
- legacy/ocr_category/prediction_from_ocr/cleaner.py
- robotoff/workers/queues.py
- Ran pre-commit hooks successfully after fixes.
Before
After
=> fix(lint): resolve flake8 W505 and E226 issues across legacy and worker modules

robotoff/insights/annotate.py, robotoff/insights/importer.py, tests/integration/insights/test_annotate.py, tests/integration/insights/test_importer.py, tests/unit/insights/test_importer.py
**Signed-off-by**: Areeb Ahmed [areebshariff@acm.org](mailto:areebshariff@acm.org)
This PR adds automatic rotation for selected images (**front**, **nutrition**, **ingredients**, and **packaging**) based on Google Cloud Vision OCR predictions.
**Key Changes**
• Introduced `ImageOrientationImporter` to process orientation predictions, filtering for selected images with high confidence (≥95%)
• Added `ImageOrientationAnnotator` to perform image rotation via the Product Opener API
• Ensured correct handling of bounding box coordinates during image rotation
• Added unit and integration tests
This addresses issue #971, reflecting the updated requirement to apply rotation only to selected images rather than all raw images.
=> feat: Implement auto-rotation for selected images using Google Cloud Vision predictions

i18n/robotoff.pot, robotoff/insights/annotate.py, robotoff/insights/importer.py, robotoff/insights/question.py, robotoff/settings.py, tests/integration/insights/test_annotate.py, tests/integration/insights/test_importer.py, tests/unit/insights/test_importer.py, tests/unit/insights/test_question.py
- use `insight.value_tag` to store the orientation
- save the image key and rev in `insight.data`
- create a question formatter to be able to use the insight type on Hunger Games
=> feat: improve image orientation insights

robotoff/prediction/ingredient_list/__init__.py, tests/integration/workers/tasks/test_import_image.py
we use '_' as word separator instead of '-' for consistency with prediction type and insight type, that cannot have '-' character in their name.
Stop the workers:
```
docker stop robotoff_worker_{1,2,3,4}
```
Launch psql:
```
docker exec -it -u postgres robotoff-postgres-1 psql robotoff
```
Run the migration:
```
UPDATE image_prediction
SET model_name = 'ingredient_detection'
WHERE type = 'ner' AND model_name = 'ingredient-detection';
```
Launch the deployment.
=> fix: rename ingredient detection model name

robotoff/workers/tasks/import_image.py, tests/integration/workers/tasks/test_import_image.py
If Product Opener ingredient parser was failing, an exception was raised during insight import, due to missing fields in insight.data.
Furthermore, the coordinates in `data.bounding_box` were not normalized in case of API error.
Solves #1600
=> fix: fix bug in `extract_ingredients_job` function

poetry.lock, pyproject.toml, robotoff/workers/update_listener.py
**Fixes** #1612
**Problem**
Update listener crashes when Redis connections drop, causing service termination.
**Solution**
* Added `backoff` with `@on_exception` on `run_update_listener()` for retry handling
* Configured exponential backoff: 10 retries, 1-minute timeout, random jitter
=> fix: Add retry logic for redis

docker/docker-livecheck.sh
with the new docker compose syntax, --services does not exist anymore and has been replaced by --services
=> chore: fix docker-livecheck.sh

robotoff/app/api.py, robotoff/batch/configs/job_configs/spellcheck.yaml
- for spellcheck import job, increase to 8 hours
- for prediction job on Google Batch, increase to 48h
=> fix: increase timeouts for spellcheck jobs

robotoff/workers/tasks/import_image.py, tests/integration/workers/tasks/test_import_image.py
A prediction was created even if all extracted entities were invalid.
I also fully tested the function using integration tests.
Fixes #1648
=> fix: fix bug in extract_ingredients_job

robotoff/insights/annotate.py, tests/unit/insights/test_annotate.py
Currently, we perform a SQL request to get the image rotation angle. We now have this information directly in `insight.data`.
=> fix: use `data['rotation']` when annotating ingredient detection insight

robotoff/scheduler/__init__.py
The dataset was not ready yet at 4PM, resulting in insights not being refreshed.
=> fix: launch refresh insight at 7PM instead of 4PM

tests/ml/test_object_detection.py
Add integration tests for Triton for most object detection models. These tests are used to check that the results of a given model has not changed when calling Triton inference server.
=> refactor: add ml tests for object detection models

data/ocr/store_regex.txt
This store does not exist, it's only a brand
Spotted by October Food Facts :
```
I sort of forgot or overlooked another one. The store Alteza is automatically added to Alteza-brand products, however, it doesn't exist. At least, I can't find such store anywhere. It has 1825 entries on the site, less than the previous 7000 Hacendado, but it's also Spanish. There's some information about this brand and its company (EMD AG), it's just not a store, being only a brand.
```
=> fix: remove store Alteza

models/triton/nutriscore/labels.txt, models/triton/nutrition_table/labels.txt, models/triton/universal_logo_detector/labels.txt
We now specify the labels directly in Robotoff.
=> chore: remove legacy labels.txt files

models/triton-config/clip/cpu.pbtxt, models/triton-config/clip/gpu.pbtxt
Otherwise, Triton crashes if clip model is not present anymore.
=> chore: move clip config to triton-config folder

robotoff/off.py
Partially fixes #1635.
Due to the use of requests Session, we sometimes also sent the cookie of a previous request.
=> fix: don't send auth cookies twice

robotoff/prediction/nutrition_extraction.py, tests/unit/prediction/test_nutrition_extraction.py
=> fix: mark invalid nutrient entity (energy_*) as such
